version: '3.8'

services:
  django:
    container_name: django
    build: ./api/docker
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
    - ./api:/usr/src/app
    ports:
      - 8000:8000